---
version: "3"
services:
    wsid1:
        image: wsid
        build: .
        environment:
          - LOG_LEVEL=DEBUG 
          - WSID_IDENTITY=http://127.0.0.1:888/manifest
          - GUNICORN_PORT=888
        network_mode: host
    wsid2:
        image: wsid
        build: .
        environment:
          - LOG_LEVEL=DEBUG 
          - WSID_IDENTITY=http://127.0.0.1:889/manifest
          - GUNICORN_PORT=889
        network_mode: host
