---
version: "3"
services:
    wsid: # kind of private thing
        image: wsid
        build: .
        environment:
          - LOG_LEVEL=DEBUG 
          - WSID_IDENTITY=http://127.0.0.1:888/manifest
          - GUNICORN_PORT=888
        network_mode: host
    validator: # same image but demo app -- does straight validation of posted output of /sign'
        image: wsid
        build: .
        volumes:
          - ./demo.py:/app/app.py
        environment:
          - LOG_LEVEL=DEBUG 
          - GUNICORN_PORT=889
        network_mode: host
